# Generated by Django 5.1.2 on 2024-10-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_data',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('caption', models.TextField()),
                ('prev_url', models.CharField(max_length=255)),
                ('new_url', models.CharField(max_length=255)),
            ],
        ),
    ]
