# Generated by Django 5.1.2 on 2024-10-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_data',
            name='ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
