# Generated by Django 5.1.2 on 2024-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0002_alter_request_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_data',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
