# Generated by Django 5.1.2 on 2024-10-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0003_alter_request_data_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request_data',
            new_name='request',
        ),
    ]
