# Generated by Django 5.1.2 on 2024-10-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0004_rename_request_data_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='request_data',
        ),
    ]
